Feature/UI table
peaksoft-school/js6-peaksoftLMS pull request #14
Opened 2022-10-12 13:29 UTC by orozobek0v

2022-10-14 04:55 UTC, aidanasm requested changes

2022-10-14 04:55 UTC, aidanasm commented on src/components/UI/UiTable.jsx
> +                     <TableCell align="left">ID</TableCell>
reusable эмес, фигманы карасанар head катары башка создор келиши мумкун

2022-10-17 04:37 UTC, merged

2022-10-17 10:35 UTC, songhee24 commented on src/components/UI/UiTable.jsx
> +                        <TableCell component="th" scope="row">
Здесь тоже самое

2022-10-17 10:35 UTC, songhee24 commented on src/components/UI/UiTable.jsx
> +                           <TableCell align="left">{item.idName}</TableCell>
так создавать не нужно это жрет процесс рендерина слишком много повторении

2022-10-17 10:35 UTC, songhee24 commented on src/components/UI/UiTable.jsx
> +                              <TableCell align="left">
как из вариантов можешь посмотреть эти ссылки 

- [deusexmachina892/reusable-table-component](https://github.com/deusexmachina892/reusable-table-component)
- [tanstack](https://tanstack.com/table/v8)